language: python
python:
    - "2.7"
before_install:
    - deactivate
    - sudo apt-get update -qq
    - sudo apt-get install -qq librsl-dev
    - sudo apt-get install -qq python-scipy python-nose python-matplotlib 
    - sudo add-apt-repository -y ppa:adrian-m-benson/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-netcdf4
    - export RSL_PATH=/usr
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
install: python setup.py build_ext --inplace
script: xvfb-run --server-args="-screen 0 1024x768x24"; nosetests -s -e "rsl" -v pyart
