language:
    - objective-c

before_install:
  - brew update
  
  # Download and install Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-3.0.5-MacOSX-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - ls -al /Users/travis
  - export PATH=/Users/travis/miniconda/bin:$PATH
  
  # Update conda
  - conda update --yes conda
  - conda update --yes conda
  
  # Create a testenv
  - conda create -n testenv --yes pip python=2.7
  - source activate testenv
  # Install dependencies from the anaconda repo to the environment
  - conda install --yes numpy scipy matplotlib netcdf4 nose

install:
  - python setup.py build_ext --inplace

script: nosetests -v --with-cov --cov pyart pyart
