language: python
python:
    - "2.7"
before_install:
    - deactivate
    - sudo apt-get update -qq
    - sudo apt-get install librsl-dev
    - sudo apt-get install -qq python-scipy python-nose python-matplotlib
    - export RSL_PATH=/usr
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
install: python setup.py build_ext --inplace
script: nosetests -s -v pyart
