language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - deactivate
    - sudo add-apt-repository -y ppa:adrian-m-benson/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose python-matplotlib 
    - sudo apt-get install -qq librsl-dev python-cvxopt python-netcdf4
    - export RSL_PATH=/usr
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
install: 
    - python -V
    - python -c "import numpy; print numpy.__version__"
    - python setup.py build_ext --inplace
script: xvfb-run --server-args="-screen 0 1024x768x24" nosetests -e "rsl" -v pyart
