language: python
python:
    - "2.6"
    - "2.7"
install: 
    - "pip install nose"
    - "pip install numpy"
    - "pip install scipy"
    - "pip install matplotlib"
    - "pip install netCDF4"
    - "python setup.py build_ext --inplace"
script: nosetests -s -v pyart
