language: python
python:
    - "2.6"
    - "2.7"
virtualenv:
  system_site_packages: true
before_install:
    - sudo add-apt-repository -y ppa:adrian-m-benson/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose python-matplotlib 
    - sudo apt-get install -qq librsl-dev python-cvxopt python-netcdf4
    - export RSL_PATH=/usr
    
install: 
    - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
    - python -V
    - python -c "import numpy; print numpy.__version__"
    - python setup.py build_ext --inplace
script: xvfb-run nosetests -e "rsl" -v pyart
