# Travis CI build script
# This is a modified version of the .travis.yml file from the scikit-learn
# project: https://github.com/scikit-learn/scikit-learn
#
# We are using Miniconda to provide a Scientific Python environment.  This
# allows us to perform a binary install of the SciPy stack on multiple
# versions of python as well as use conda and binstar to install additional
# module which are not in the default Anaconda repository.
#
language: python
python:
    - "2.7"
#    - "2.6"        # disable while testing, also broken
before_install:
  # Download and install Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda
  - conda update --yes conda
  - conda update --yes conda
  # Create a testenv
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # Install dependencies from the anaconda repo to the environment
  - conda install --yes numpy scipy matplotlib netcdf4 basemap nose
  # Install additional packages from Binstar
  - conda install --yes -c http://conda.binstar.org/jjhelmus pyproj trmm_rsl

install:
  - export RSL_PATH=~/anaconda/env/testenv
  - python setup.py build_ext --inplace
script: xvfb-run nosetests -v pyart
