# Travis CI build script
# This is a modified version of the .travis.yml file from the scikit-learn
# project: https://github.com/scikit-learn/scikit-learn
#
# We are using Miniconda to provide a Python environment.  This
# allows us to perform a conda based install of the SciPy stack on multiple
# versions of python as well as use conda and binstar to install additional
# module which are not in the default Anaconda repository.
#
language: python
python:
    - "2.7"
before_install:
  # Download and install Miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda
  - conda update --yes conda
  - conda update --yes conda
  # Create a testenv
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # Install dependencies from the anaconda repo to the environment
  - conda install --yes numpy scipy matplotlib netcdf4 nose
  - conda install --yes basemap
  # Install RSL from binstar
  - conda install --yes -c http://conda.binstar.org/jjhelmus trmm_rsl
  # LP solver cylp and its dependancy CBC
  - conda install --yes -c http://conda.binstar.org/jjhelmus cbc cylp
  # LP solvers pyglpk based on GLPK
  - sudo apt-get update -qq
  - sudo apt-get install -qq libglpk-dev
  - conda install --yes -c http://conda.binstar.org/jjhelmus pyglpk
  # LP solvers cvxopt with GLPK support
  - conda install --yes -c http://conda.binstar.org/jjhelmus cvxopt_glpk
  - conda install --yes sphinx
install:
  - export RSL_PATH=~/anaconda/envs/testenv
  - python setup.py install

script: 
  - pwd
  - cd doc
  - pwd
  - make html
  - cd
  - pwd
  - xvfb-run nosetests -exe pyart
